enable-magisk-update = false
parallel-jobs = 1
cli-source = "MorpheApp/morphe-cli"
patches-source = "MorpheApp/morphe-patches"
rv-brand = "Morphe"

[YouTube]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
arch = "arm64-v8a"
version = "auto"

[YouTube-Music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "arm64-v8a"
version = "auto"
